# Generated by Django 4.2 on 2025-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='display_picture',
            field=models.FileField(upload_to='profiles/'),
        ),
    ]
