# Generated by Django 4.2 on 2025-11-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwday7app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='author_name',
            new_name='author',
        ),
    ]
